CREATE TABLE sites (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  site_number INTEGER NOT NULL,
  tl_address TEXT,
  tl_city TEXT,
  tl_state CHARACTER VARYING(2),
  tl_zip_code INTEGER,
  tl_road_side TEXT,
  tl_phone_number TEXT,
  trout_lake_water BOOLEAN,
  land_company TEXT,
  owners_association TEXT,
  user_id INTEGER  
    REFERENCES users(id) ON DELETE CASCADE
);