CREATE TABLE bills (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  year INTEGER NOT NULL,
  bill_amount MONEY NOT NULL,
  bill_type TEXT NOT NULL,
  bill_due_date DATE NOT NULL,
  bill_status TEXT DEFAULT 'DUE' NOT NULL,
  paid_in_full_date DATE, 
  site_id INTEGER
    REFERENCES sites(id) ON DELETE CASCADE,
  updatedAt TIMESTAMPTZ DEFAULT now() NOT NULL
);